services:
  postgres:
    container_name: postgres-sql-fighthub
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: fighthub
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - fighthub-network
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-fighthub
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    restart: unless-stopped


  keycloak:
    container_name: keycloak-fighthub
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - fighthub-network
    command:
      - "start-dev"

networks:
  fighthub-network:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local