spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    #url: jdbc:postgresql://localhost:5433/fighthub
    #username: admin
    #password: admin
    url: jdbc:postgresql://aws-0-eu-west-2.pooler.supabase.com:6543/postgres?
    username: postgres.srhjieykuiezyiisnvgl
    password: 79039350Bb+
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: "chipicranium@gmail.com"
    password: "pjen hzlc wboi orlb"
    properties:
      mail:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

logging:
  level:
    javax.mail: DEBUG
    org.springframework.mail: DEBUG

springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    path: /api/v1/swagger-ui.html

server:
  servlet:
    context-path: /api/v1
  tomcat:
    max-http-form-post-size: 50MB
    max-swallow-size: -1

upload:
  path: "uploads"

application:
  security:
    jwt:
      secret-key: LmtC4QHX8ZP3Lgf8KvLXG3ZsDbYxFPXqftCvcBDV1a8=
      expiration: 604800000
  email:
    from: "chipicranium@gmail.com"
    activation-url: "http://localhost:8080/api/v1/auth/activate-account"

  openai:
    api-key: ${OPENAI_API_KEY}
