spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    path: /api/v1/swagger-ui.html

server:
  servlet:
    context-path: /api/v1